.TH MYSTRNCPY 1 "September 2026" "OS Assignment 01" "User Commands"

.SH NAME
mystrncpy \- copy a limited number of characters

.SH SYNOPSIS
.B int mystrncpy(char *dest, const char *src, int n);

.SH DESCRIPTION
The mystrncpy function copies at most n characters from the source string to the destination string and terminates the destination string.

.SH AUTHOR
Aleeza - BSDSF24A014
